Repository hyphacoop/organizing, pull requests merged in 2019-12, with the labels that each got.

#146 Added sync-labels workflow for GitHub Actions
  .github/workflows/sync-labels.yml
Labels: wg:infra-ops

#166 Create 2019-12-10-finance-wg-meeting.md
  2019-12-10-finance-wg-meeting.md
Labels: wg:finance

#157 Create 2019-11-26-finance-wg-meeting.md
  2019-11-26-finance-wg-meeting.md
Labels: wg:finance

#171 Ensure labels only sync on commits to github action config
  .github/workflows/sync-labels.yml
Labels: [priority-★☆☆], wg:infra-ops

#170 Improve templates: linebreaks and docs
  -meeting-template.md
  -standup-template.md
Labels: [priority-★☆☆], wg:infra-ops
