Repository hyphacoop/organizing, pull requests merged in 2020-03, with the labels that each got.

#231 Archive 2020-03-16 infrastructure meeting notes
  _posts/meeting-notes/2020-03-16-infrastructure.md
Labels: wg:infrastructure

#237 Slight nav rearrangement and fixing non-W3C html
  _config.yml
  _includes/nav.html
  _includes/private-redirect.html
  assets/main.scss
Labels: [priority-★☆☆], wg:operations

#238 Add folder and 2020 Q1 okr notes
  _posts/okrs/2020-01-07-Q1-goal-setting.md
Labels: wg:operations
